require("ch3ber.options")
require("ch3ber.keymaps")
require("ch3ber.plugins")
require("ch3ber.colorscheme")
vim.cmd("source $HOME/.config/nvim/lua/ch3ber/coc.vim")
require("ch3ber.nvim-tree")
require("ch3ber.telescope")
require("ch3ber.comment")
--require("ch3ber.cmp")
--require("ch3ber.lsp")
