#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

#wallpapers
#feh -z --bg-fill ~/Imágenes/wallpapers/**
feh -z --bg-fill ~/Imágenes/wallpapers/minimalist/wallhaven-zxr9mj_2560x1440.png

#toggle layouts
#setxkbmap -layout us,es -option grp:win_space_toggle
setxkbmap -layout us,es -option grp:shift_caps_toggle

#polybar
~/.config/polybar/launch.sh --blocks

#mouse window focus
bspc config focus_follows_pointer true

#quit borders of polybar
picom --experimental-backends &
bspc config border_width 0

#set cursor
xsetroot -cursor_name left_ptr &
